/**
 * The showcase data model.
 *
 * Everything comparable on this site is a *plate*: one subject, two arms, the
 * same brief. Pages are generated from this schema rather than hand-authored,
 * so adding a benchmark is a data change, not a page.
 *
 * Two rules this schema exists to enforce:
 *
 * 1. `provenance` is required. A plate is either `measured` - both arms were
 *    generated by separate agent runs and scored by scripts/ - or `authored`,
 *    meaning the arms were built to illustrate a documented difference. The UI
 *    prints which. An honest "no baseline equivalent" beats a fabricated one.
 *
 * 2. There is no overall score field, by design. scripts/score.py returns the
 *    *measured* half only; hierarchy, signature, content fit, copy, state
 *    coverage and concept are judged, and the two have different epistemic
 *    status. They stay in separate fields so the UI cannot blend them.
 */

import type { ReactNode } from "react";

/* ------------------------------------------------------------------ arms */

export type ArmKind = "baseline" | "parti";

export const ARM_LABEL: Record<ArmKind, string> = {
  baseline: "Without Parti",
  parti: "With Parti",
};

/** Arm A / Arm B - the neutral labels, used where "without/with" would bias. */
export const ARM_PLATE: Record<ArmKind, string> = {
  baseline: "ARM A",
  parti: "ARM B",
};

/* ------------------------------------------------- direction (6 axes) */

/** The six axes from SKILL.md step 3. Two directions differing on fewer than
 *  two of these are one direction. */
export type Density = "sparse" | "measured" | "dense";
export type Structure =
  | "grid-strict"
  | "editorial-asymmetric"
  | "modular-bento"
  | "canvas-freeform";
export type TypeVoice =
  | "neutral-utility"
  | "editorial-serif"
  | "display-eccentric"
  | "mono-technical";
export type Chroma =
  | "monochrome+accent"
  | "duotone"
  | "full-spectrum"
  | "achromatic-with-material";
export type MotionPosture = "still" | "responsive-only" | "choreographed" | "ambient";
export type Depth = "flat" | "layered-shadow" | "material-translucent" | "spatial";

export interface DirectionAxes {
  density: Density;
  structure: Structure;
  typeVoice: TypeVoice;
  chroma: Chroma;
  motionPosture: MotionPosture;
  depth: Depth;
}

export const AXIS_LABEL: Record<keyof DirectionAxes, string> = {
  density: "Density",
  structure: "Structure",
  typeVoice: "Type voice",
  chroma: "Chroma",
  motionPosture: "Motion posture",
  depth: "Depth",
};

export interface Direction {
  name: string;
  /** One sentence about what it believes about the user. */
  thesis: string;
  nearestMovement: string;
  /** Where it departs from that movement - required, or it is just the movement. */
  departure: string;
  axes: DirectionAxes;
  /** The element it is remembered by. */
  signature: string;
  /** What it gives up. Every direction gives something up. */
  cost: string;
}

/* ------------------------------------------------------------- tokens */

export interface ColorToken {
  name: string;
  value: string;
  oklch?: string;
  role: string;
  /** Stated contrast, e.g. "6.21:1 on --paper". Absent for non-text tokens. */
  contrast?: string;
}

export interface ScaleToken {
  name: string;
  value: string;
  role: string;
}

export interface TokenSet {
  color: ColorToken[];
  type: ScaleToken[];
  space: ScaleToken[];
  shape: ScaleToken[];
  motion: ScaleToken[];
}

/* -------------------------------------------------------------- states */

export type StateName =
  | "default"
  | "hover"
  | "focus"
  | "active"
  | "disabled"
  | "loading"
  | "empty"
  | "error"
  | "success"
  | "overflow";

export interface StateSpec {
  name: StateName;
  /** What this state must communicate. Not how it looks - why it exists. */
  intent: string;
  /** Whether the arm actually implements it. The gap is the finding. */
  implemented: boolean;
  note?: string;
}

/* ------------------------------------------------------------ findings */

/** The "why this is different" panel, §20. Four fields, in this order. */
export interface Finding {
  finding: string;
  whyItHappens: string;
  partiDecision: string;
  result: string;
}

/* ------------------------------------------------- the difference matrix */

export interface MatrixRow {
  dimension: string;
  baseline: string;
  parti: string;
}

/* ---------------------------------------------------------------- arms */

export interface BaselineArm {
  /** Exactly what the baseline agent was given. */
  prompt: string;
  /** Key into the component registry - resolves to a real React component. */
  componentKey: string;
  /** Why it made the choices it made, stated fairly. */
  rationale: string;
  sourcePath: string;
  notes?: string[];
}

export interface PartiArm {
  prompt: string;
  /** Parti commands actually invoked, in order. */
  commands: string[];
  direction: Direction;
  componentKey: string;
  rationale: string;
  sourcePath: string;
  tokens: TokenSet;
  states: StateSpec[];
  findings: Finding[];
  notes?: string[];
}

/* ------------------------------------------------------------ measured */

export interface MeasuredArm {
  score: number;
  band: string;
  tells: number;
  motionRules: number;
  shadows: number;
  hexLiterals: number;
  tokenSpec: boolean;
  designMd: boolean;
  dimensions: Record<string, number>;
}

/* ------------------------------------------------------------- example */

export type Category =
  | "Landing page"
  | "Dashboard"
  | "SaaS product"
  | "Finance"
  | "Marketing"
  | "Developer tool"
  | "E-commerce"
  | "Analytics"
  | "Documentation"
  | "Data-dense";

export interface ShowcaseExample {
  id: string;
  slug: string;
  plate: string;
  title: string;
  category: Category;
  /** One line, for the gallery card. */
  brief: string;
  /** The full brief, verbatim, given identically to both arms. */
  sharedBrief: string;
  tags: string[];
  /** measured = two real agent runs, scored by scripts/.
   *  authored = built to illustrate a documented difference. Printed in the UI. */
  provenance: "measured" | "authored";
  /** The one checkable thing to look at first. */
  tell: string;
  baseline: BaselineArm;
  parti: PartiArm;
  matrix: MatrixRow[];
  measured?: { baseline: MeasuredArm; parti: MeasuredArm };
}

/* ----------------------------------------------------------- component */

export type ComponentGroup = "Marketing" | "Product" | "Forms" | "Content";

export interface ComponentPair {
  slug: string;
  name: string;
  group: ComponentGroup;
  /** What this component is for, in one line. */
  brief: string;
  prompt: string;
  tell: string;
  baseline: { componentKey: string; rationale: string; sourcePath: string };
  parti: {
    componentKey: string;
    rationale: string;
    sourcePath: string;
    direction: string;
    commands: string[];
  };
  /** What the baseline arm actually implements. */
  states: StateSpec[];
  /** What the parti arm implements. The delta is the finding. */
  partiStates: StateSpec[];
  findings: Finding[];
  /** Optional per-component override; otherwise the group matrix is used. */
  matrix?: MatrixRow[];
}

/* ------------------------------------------------------------ registry */

export interface RegistryEntry {
  key: string;
  /** Repo-relative path of the file that actually renders. The code viewer
   *  reads this file at build time - snippets are never hand-written. */
  sourcePath: string;
  /** Full-bleed arms opt out of the preview shell's padding. */
  bleed?: boolean;
  render: () => ReactNode;
}
