import type { ComponentPair, StateSpec, StateName } from "@/lib/schema";

/**
 * The component comparison library. Generated by design/gen_components.py -
 * edit the authored strings there, not here.
 *
 * `tell` is the most valuable field on each entry: the one specific, checkable
 * thing to look at first. A comparison that only says "the parti one is nicer"
 * is not evidence, and a reader who is told exactly where to look is able to
 * disagree with us, which is the point.
 *
 * State coverage is recorded per arm because the gap between the two is
 * usually the largest real difference, and it is completely invisible in a
 * screenshot.
 */

const INTENT: Record<StateName, string> = {
  "default": "The resting state. What the reader sees before touching anything.",
  "hover": "Pointer feedback only - never the sole carrier of information, since it does not exist on touch.",
  "focus": "Keyboard position, visible at 3:1 against its adjacent ground.",
  "active": "The moment of press. Confirms the input landed.",
  "disabled": "Unavailable, with the reason available rather than merely dimmed.",
  "loading": "Waiting, shaped like the content that is coming.",
  "empty": "Nothing to show, naming the cause and offering the next action.",
  "error": "What broke, why, and what to do next.",
  "success": "Confirmation that persists long enough to be read.",
  "overflow": "Ten times the expected content, without the layout breaking."
};

function states(
  names: StateName[],
  built: StateName[],
): StateSpec[] {
  return names.map((n) => ({
    name: n,
    intent: INTENT[n],
    implemented: built.includes(n),
  }));
}

export const COMPONENT_PAIRS: ComponentPair[] = [

  {
    slug: "navigation-bar",
    name: "Navigation Bar",
    group: "Marketing",
    brief: "Primary site navigation for a developer runtime.",
    prompt: "Build a navigation bar for Cadence, a runtime for production AI agents. Primary site navigation for a developer runtime.",
    tell: "Count the affordances. The baseline navbar is a centred pill with a gradient CTA; the parti one is flush, carries the run sequence number, and its CTA names the actual next step rather than 'Get started'.",
    baseline: {
      componentKey: "marketing/navigation-bar/baseline",
      sourcePath: "src/arms/components/marketing/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "marketing/navigation-bar/parti",
      sourcePath: "src/arms/components/marketing/parti.tsx",
      direction: "append-only",
      commands: ["explore", "tokens", "build", "deslop"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active"]),
    partiStates: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active", "overflow"]),
    findings: [
      {
        finding: "A floating rounded navbar detached from the top edge",
        whyItHappens: "It is the single most-copied navigation pattern in current generated output, so it is what the model reaches for before reading the brief.",
        partiDecision: "Flush to the top on a hairline, with the run-sequence gutter continuing through it.",
        result: "The navigation stops being a separate decorative object and becomes the first record of the journal the page is.",
      },
      {
        finding: "CTA labelled 'Get started'",
        whyItHappens: "It is the highest-frequency CTA string on the web, so it is the safest completion.",
        partiDecision: "The control names what happens: it opens a run you can step through.",
        result: "A skeptical engineer can tell what the click costs before making it.",
      }
    ],
  },
  {
    slug: "announcement-bar",
    name: "Announcement Bar",
    group: "Marketing",
    brief: "A dismissible strip announcing a change above the navigation.",
    prompt: "Build a announcement bar for Cadence, a runtime for production AI agents. A dismissible strip announcing a change above the navigation.",
    tell: "The baseline bar is a gradient strip with an emoji and a chevron. The parti one is a changelog line with a version and a date, because that is what this audience wants from an announcement.",
    baseline: {
      componentKey: "marketing/announcement-bar/baseline",
      sourcePath: "src/arms/components/marketing/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "marketing/announcement-bar/parti",
      sourcePath: "src/arms/components/marketing/parti.tsx",
      direction: "append-only",
      commands: ["explore", "tokens", "build", "deslop"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active"]),
    partiStates: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active", "overflow"]),
    findings: [
      {
        finding: "Gradient strip with an emoji and the word New",
        whyItHappens: "Announcement bars in training data are marketing furniture, so marketing furniture is what gets produced.",
        partiDecision: "One appended record: version, date, one clause, and a link to the diff.",
        result: "The bar becomes readable at a glance by someone deciding whether to care, and it dismisses without losing the information.",
      }
    ],
  },
  {
    slug: "hero",
    name: "Hero",
    group: "Marketing",
    brief: "The first screen: what this is, who it is for, and one proof.",
    prompt: "Build a hero for Cadence, a runtime for production AI agents. The first screen: what this is, who it is for, and one proof.",
    tell: "The clearest single contrast in the library. The baseline hero centres a headline over a gradient with a product screenshot; the parti hero renders a real failed-then-resumed run with a working replay scrubber.",
    baseline: {
      componentKey: "marketing/hero/baseline",
      sourcePath: "src/arms/components/marketing/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "marketing/hero/parti",
      sourcePath: "src/arms/components/marketing/parti.tsx",
      direction: "append-only",
      commands: ["explore", "tokens", "build", "deslop"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active"]),
    partiStates: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active", "overflow"]),
    findings: [
      {
        finding: "Centred headline, subhead, two buttons, product screenshot",
        whyItHappens: "It is the structural default of nearly every SaaS hero in the training set, and it is genuinely safe - it works, which is exactly why it converges.",
        partiDecision: "Show the artifact instead of describing it: an actual span waterfall from a run that was interrupted mid-execution and resumed.",
        result: "The proof is on screen in the first viewport instead of being promised three sections down.",
      },
      {
        finding: "A gradient mesh behind the headline",
        whyItHappens: "Decorative background gradients are a strong prior for 'this is a modern product page'.",
        partiDecision: "No background treatment at all. The ground is one flat value and the interest comes from the run record.",
        result: "Nothing competes with the one thing on the page worth looking at.",
      },
      {
        finding: "A screenshot of a dashboard as the hero visual",
        whyItHappens: "A picture of the product is the conventional way to show the product.",
        partiDecision: "Render the product. It is a web app; a live component costs the same as an image and can be interacted with.",
        result: "The visitor can step through a run in the hero rather than squinting at a picture of one.",
      }
    ],
  },
  {
    slug: "cta",
    name: "CTA",
    group: "Marketing",
    brief: "The closing call to action.",
    prompt: "Build a cta for Cadence, a runtime for production AI agents. The closing call to action.",
    tell: "Read the two button labels. One offers to start a free trial; the other names the specific next step this audience would actually take.",
    baseline: {
      componentKey: "marketing/cta/baseline",
      sourcePath: "src/arms/components/marketing/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "marketing/cta/parti",
      sourcePath: "src/arms/components/marketing/parti.tsx",
      direction: "append-only",
      commands: ["explore", "tokens", "build", "deslop"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active"]),
    partiStates: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active", "overflow"]),
    findings: [
      {
        finding: "'Start your free trial' over a saturated band",
        whyItHappens: "The pattern is so common it arrives without a decision being made.",
        partiDecision: "The closing record of the run journal, with the two real next steps named.",
        result: "The page ends where it began - as one continuous artifact - rather than switching register to sell.",
      }
    ],
  },
  {
    slug: "feature-grid",
    name: "Feature Grid",
    group: "Marketing",
    brief: "Four capabilities, presented so a skeptic can evaluate them.",
    prompt: "Build a feature grid for Cadence, a runtime for production AI agents. Four capabilities, presented so a skeptic can evaluate them.",
    tell: "Look at the icons. The baseline has four rounded-square gradient tiles above four headings; the parti arm has none, and uses the offset in the run where each capability applies.",
    baseline: {
      componentKey: "marketing/feature-grid/baseline",
      sourcePath: "src/arms/components/marketing/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "marketing/feature-grid/parti",
      sourcePath: "src/arms/components/marketing/parti.tsx",
      direction: "append-only",
      commands: ["explore", "tokens", "build", "deslop"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active"]),
    partiStates: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active", "overflow"]),
    findings: [
      {
        finding: "Rounded-square gradient icon tiles above each feature heading",
        whyItHappens: "Feature grids in the training set almost always carry decorative icons, and the icons carry no information in any of them.",
        partiDecision: "The sequence marker each capability applies at, drawn from the run itself.",
        result: "The numbering now encodes something true - where in an execution the feature matters - rather than being 01/02/03.",
      },
      {
        finding: "Three or four equal cards in a symmetric row",
        whyItHappens: "Equal cards are the least-risk layout, so they are the default completion.",
        partiDecision: "Records of unequal height on one grid, sized by how much each actually needs to say.",
        result: "The layout stops implying the four things are equally important when they are not.",
      }
    ],
  },
  {
    slug: "logo-cloud",
    name: "Logo Cloud",
    group: "Marketing",
    brief: "Social proof by association.",
    prompt: "Build a logo cloud for Cadence, a runtime for production AI agents. Social proof by association.",
    tell: "The baseline shows six grey company wordmarks. The parti arm shows what this audience actually evaluates on, because an unnamed logo row is unfalsifiable.",
    baseline: {
      componentKey: "marketing/logo-cloud/baseline",
      sourcePath: "src/arms/components/marketing/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "marketing/logo-cloud/parti",
      sourcePath: "src/arms/components/marketing/parti.tsx",
      direction: "append-only",
      commands: ["explore", "tokens", "build", "deslop"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active"]),
    partiStates: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active", "overflow"]),
    findings: [
      {
        finding: "A row of desaturated company logos",
        whyItHappens: "It is the standard social-proof unit and it reads as credible at a glance.",
        partiDecision: "State the deployment shape instead - runtime, scale, and workload class - since those are checkable and a logo is not.",
        result: "The section says something a skeptical reader can act on, and it does not require inventing customers.",
      }
    ],
  },
  {
    slug: "testimonial",
    name: "Testimonial",
    group: "Marketing",
    brief: "One quote, presented so it is worth reading.",
    prompt: "Build a testimonial for Cadence, a runtime for production AI agents. One quote, presented so it is worth reading.",
    tell: "Neither arm invents a named person at a named company. Compare what each does with that constraint instead.",
    baseline: {
      componentKey: "marketing/testimonial/baseline",
      sourcePath: "src/arms/components/marketing/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "marketing/testimonial/parti",
      sourcePath: "src/arms/components/marketing/parti.tsx",
      direction: "append-only",
      commands: ["explore", "tokens", "build", "deslop"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active"]),
    partiStates: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active", "overflow"]),
    findings: [
      {
        finding: "A quote card with a circular avatar and a full name at a real company",
        whyItHappens: "Testimonials in training data have avatars and names, so the model fabricates them.",
        partiDecision: "Attribute by role and system, and set the quote as a journal entry rather than a card.",
        result: "The proof is honest and the layout stops needing a face it does not have.",
      }
    ],
  },
  {
    slug: "pricing",
    name: "Pricing",
    group: "Marketing",
    brief: "Three tiers and the decision between them.",
    prompt: "Build a pricing for Cadence, a runtime for production AI agents. Three tiers and the decision between them.",
    tell: "Look at how the recommended tier is marked. One lifts it with a shadow and a scale transform; the other steps the ground and prints a reason.",
    baseline: {
      componentKey: "marketing/pricing/baseline",
      sourcePath: "src/arms/components/marketing/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "marketing/pricing/parti",
      sourcePath: "src/arms/components/marketing/parti.tsx",
      direction: "append-only",
      commands: ["explore", "tokens", "build", "deslop"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active"]),
    partiStates: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active", "overflow"]),
    findings: [
      {
        finding: "The middle tier lifted with a shadow, a border glow and 'Most popular'",
        whyItHappens: "Emphasis-by-elevation is the reflex, and 'Most popular' is the default badge string.",
        partiDecision: "One ground step and a printed reason for the recommendation.",
        result: "The emphasis survives grayscale, and the badge says why rather than asserting popularity.",
      },
      {
        finding: "Pricing per seat",
        whyItHappens: "Per-seat is the dominant SaaS model in the training set.",
        partiDecision: "Price on the unit that does the work - runs and retained history - because that is what this product consumes.",
        result: "The pricing page stops requiring a translation step before an engineer can estimate their bill.",
      }
    ],
  },
  {
    slug: "faq",
    name: "FAQ",
    group: "Marketing",
    brief: "The objections, answered.",
    prompt: "Build a faq for Cadence, a runtime for production AI agents. The objections, answered.",
    tell: "Both arms use a disclosure. Check what happens without JavaScript, and check what the questions are - one set is generic, one set is the objections this audience actually raises.",
    baseline: {
      componentKey: "marketing/faq/baseline",
      sourcePath: "src/arms/components/marketing/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "marketing/faq/parti",
      sourcePath: "src/arms/components/marketing/parti.tsx",
      direction: "append-only",
      commands: ["explore", "tokens", "build", "deslop"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active"]),
    partiStates: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active", "overflow"]),
    findings: [
      {
        finding: "Questions like 'Is there a free trial?' and 'Can I cancel anytime?'",
        whyItHappens: "Generic FAQ content is the highest-probability completion under an FAQ heading.",
        partiDecision: "The actual objections: what happens when a deploy lands mid-run, how replay handles a changed tool signature, what the event log costs at volume.",
        result: "The section does work instead of occupying space.",
      }
    ],
  },
  {
    slug: "footer",
    name: "Footer",
    group: "Marketing",
    brief: "The colophon and the link farm.",
    prompt: "Build a footer for Cadence, a runtime for production AI agents. The colophon and the link farm.",
    tell: "Count the columns. Four columns of links is the reflex; the parti footer prints what the document is and what verified it.",
    baseline: {
      componentKey: "marketing/footer/baseline",
      sourcePath: "src/arms/components/marketing/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "marketing/footer/parti",
      sourcePath: "src/arms/components/marketing/parti.tsx",
      direction: "append-only",
      commands: ["explore", "tokens", "build", "deslop"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active"]),
    partiStates: states(["default", "hover", "focus", "active", "overflow"], ["default", "hover", "focus", "active", "overflow"]),
    findings: [
      {
        finding: "Four columns of links, several of which go nowhere",
        whyItHappens: "Footers in the training set have four columns, so four columns get generated regardless of how many destinations exist.",
        partiDecision: "As many columns as there are real destinations, plus a colophon.",
        result: "The footer stops advertising pages that do not exist.",
      }
    ],
  },
  {
    slug: "dashboard-header",
    name: "Dashboard Header",
    group: "Product",
    brief: "The top bar of a research workspace.",
    prompt: "Build a dashboard header for Ledgerline, a research workspace for independent investors. The top bar of a research workspace.",
    tell: "The baseline header has a search field, a bell, and an avatar. The parti one carries the date of the last session, because the job is re-entry after two weeks away.",
    baseline: {
      componentKey: "product/dashboard-header/baseline",
      sourcePath: "src/arms/components/product/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "product/dashboard-header/parti",
      sourcePath: "src/arms/components/product/parti.tsx",
      direction: "marginalia",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus", "loading", "empty", "error", "overflow"]),
    findings: [
      {
        finding: "Search, notifications bell, avatar menu",
        whyItHappens: "It is the canonical app-shell header and it is not wrong - it is simply unexamined.",
        partiDecision: "The header states when you were last here and what changed since, which is the first question this user has.",
        result: "The most valuable information on the screen is in the first place the eye lands.",
      }
    ],
  },
  {
    slug: "sidebar",
    name: "Sidebar",
    group: "Product",
    brief: "Primary workspace navigation.",
    prompt: "Build a sidebar for Ledgerline, a research workspace for independent investors. Primary workspace navigation.",
    tell: "Compare the icons. One arm gives every nav item an icon; the other gives none, because the items are words this user reads dozens of times a day.",
    baseline: {
      componentKey: "product/sidebar/baseline",
      sourcePath: "src/arms/components/product/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "product/sidebar/parti",
      sourcePath: "src/arms/components/product/parti.tsx",
      direction: "marginalia",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus", "loading", "empty", "error", "overflow"]),
    findings: [
      {
        finding: "An icon beside every navigation label",
        whyItHappens: "Sidebars in the training set have icons, so icons get added whether or not they disambiguate anything.",
        partiDecision: "Text only, in the margin rail, with the count of what is inside each section.",
        result: "Nothing has to be learned, and the counts add information the icons were not carrying.",
      }
    ],
  },
  {
    slug: "stat-cards",
    name: "Stat Cards",
    group: "Product",
    brief: "The portfolio summary figures.",
    prompt: "Build a stat cards for Ledgerline, a research workspace for independent investors. The portfolio summary figures.",
    tell: "Count the KPI tiles. The parti arm has fewer and they are not cards, because four big numbers in rounded boxes is a consumer-analytics convention borrowed from a different job.",
    baseline: {
      componentKey: "product/stat-cards/baseline",
      sourcePath: "src/arms/components/product/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "product/stat-cards/parti",
      sourcePath: "src/arms/components/product/parti.tsx",
      direction: "marginalia",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus", "loading", "empty", "error", "overflow"]),
    findings: [
      {
        finding: "Four equal cards with a large number and a green or red delta arrow",
        whyItHappens: "The KPI tile row is the single strongest visual prior for the word 'dashboard'.",
        partiDecision: "Ruled figures in the margin with the period they cover stated, and no colour on the delta.",
        result: "A minus three percent fortnight stops outranking an unresolved question in a five-year thesis.",
      },
      {
        finding: "A green up-arrow and a red down-arrow on every figure",
        whyItHappens: "Directional colour on a number is the reflex for financial data.",
        partiDecision: "Colour is reserved for one meaning: this needs your judgement.",
        result: "The one thing that genuinely needs attention becomes the only coloured thing on the screen.",
      }
    ],
  },
  {
    slug: "data-table",
    name: "Data Table",
    group: "Product",
    brief: "The positions table.",
    prompt: "Build a data table for Ledgerline, a research workspace for independent investors. The positions table.",
    tell: "Look at the numerals. Both arms are competent; check whether the columns stay aligned when a value changes, and what happens at 375px.",
    baseline: {
      componentKey: "product/data-table/baseline",
      sourcePath: "src/arms/components/product/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "product/data-table/parti",
      sourcePath: "src/arms/components/product/parti.tsx",
      direction: "marginalia",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus", "loading", "empty", "error", "overflow"]),
    findings: [
      {
        finding: "Proportional figures in numeric columns",
        whyItHappens: "Body text defaults to proportional numerals and nobody notices until a column jitters on refresh.",
        partiDecision: "Tabular numerals on every value that is read as data.",
        result: "Columns hold still, which is the difference between a table you can scan and one you have to read.",
      },
      {
        finding: "The table becomes a horizontal scroll at mobile width",
        whyItHappens: "Shrinking is the default responsive behaviour for a table.",
        partiDecision: "Below the breakpoint it stops being a table and becomes records - which is what the margin structure already was.",
        result: "The data is readable at 375px instead of merely present.",
      }
    ],
  },
  {
    slug: "chart-panel",
    name: "Chart Panel",
    group: "Product",
    brief: "Price history against cost basis.",
    prompt: "Build a chart panel for Ledgerline, a research workspace for independent investors. Price history against cost basis.",
    tell: "Check what the chart is for. One draws a price line; the other marks where the thesis was written against it.",
    baseline: {
      componentKey: "product/chart-panel/baseline",
      sourcePath: "src/arms/components/product/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "product/chart-panel/parti",
      sourcePath: "src/arms/components/product/parti.tsx",
      direction: "marginalia",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus", "loading", "empty", "error", "overflow"]),
    findings: [
      {
        finding: "A price chart with a gradient area fill under the line",
        whyItHappens: "Area gradients are the default chart decoration.",
        partiDecision: "A flat line with the cost basis ruled across it and the thesis dates marked in the margin.",
        result: "The chart answers the question this user actually has - was I right - rather than showing that the price moved.",
      }
    ],
  },
  {
    slug: "filter-bar",
    name: "Filter Bar",
    group: "Product",
    brief: "Narrowing the position list.",
    prompt: "Build a filter bar for Ledgerline, a research workspace for independent investors. Narrowing the position list.",
    tell: "Check whether the applied filters are still visible after you scroll away from the bar.",
    baseline: {
      componentKey: "product/filter-bar/baseline",
      sourcePath: "src/arms/components/product/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "product/filter-bar/parti",
      sourcePath: "src/arms/components/product/parti.tsx",
      direction: "marginalia",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus", "loading", "empty", "error", "overflow"]),
    findings: [
      {
        finding: "Filters applied but not restated near the results",
        whyItHappens: "The control and its effect get designed separately, so the connection between them is lost.",
        partiDecision: "The active filter is printed in the margin beside the result count, and the empty state names it.",
        result: "A user who scrolls back to an unexpectedly short list can see why it is short.",
      }
    ],
  },
  {
    slug: "search",
    name: "Search",
    group: "Product",
    brief: "Finding a company or a filing.",
    prompt: "Build a search for Ledgerline, a research workspace for independent investors. Finding a company or a filing.",
    tell: "Type nothing and look at what each arm offers.",
    baseline: {
      componentKey: "product/search/baseline",
      sourcePath: "src/arms/components/product/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "product/search/parti",
      sourcePath: "src/arms/components/product/parti.tsx",
      direction: "marginalia",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus", "loading", "empty", "error", "overflow"]),
    findings: [
      {
        finding: "An empty dropdown until the user types",
        whyItHappens: "The populated state is the one that gets designed.",
        partiDecision: "Recent tickers and open theses on focus, before any keystroke.",
        result: "The most common search - back to what I was reading - takes zero characters.",
      }
    ],
  },
  {
    slug: "tabs",
    name: "Tabs",
    group: "Product",
    brief: "Switching between thesis, filings, and notes.",
    prompt: "Build a tabs for Ledgerline, a research workspace for independent investors. Switching between thesis, filings, and notes.",
    tell: "Watch the indicator when you switch. Then switch with the keyboard.",
    baseline: {
      componentKey: "product/tabs/baseline",
      sourcePath: "src/arms/components/product/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "product/tabs/parti",
      sourcePath: "src/arms/components/product/parti.tsx",
      direction: "marginalia",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus", "loading", "empty", "error", "overflow"]),
    findings: [
      {
        finding: "The active tab marked only by colour",
        whyItHappens: "Colour is the cheapest way to mark selection and it looks fine to a sighted reviewer.",
        partiDecision: "Weight, rule, and position all change, so selection survives grayscale.",
        result: "The component stops depending on one channel to carry its only state.",
      }
    ],
  },
  {
    slug: "modal",
    name: "Modal",
    group: "Product",
    brief: "A focused task over the workspace.",
    prompt: "Build a modal for Ledgerline, a research workspace for independent investors. A focused task over the workspace.",
    tell: "Press Escape. Then Tab past the last control and see where focus goes.",
    baseline: {
      componentKey: "product/modal/baseline",
      sourcePath: "src/arms/components/product/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "product/modal/parti",
      sourcePath: "src/arms/components/product/parti.tsx",
      direction: "marginalia",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus", "loading", "empty", "error", "overflow"]),
    findings: [
      {
        finding: "Focus not trapped, and not returned on close",
        whyItHappens: "The visual design of a modal is separable from its focus management, so the focus half gets skipped.",
        partiDecision: "Focus moves in on open, is trapped while open, and returns to the trigger on close.",
        result: "The dialog is operable without a mouse, which is a floor rather than a feature.",
      }
    ],
  },
  {
    slug: "drawer",
    name: "Drawer",
    group: "Product",
    brief: "A side panel for a secondary task.",
    prompt: "Build a drawer for Ledgerline, a research workspace for independent investors. A side panel for a secondary task.",
    tell: "Check what the drawer covers, and whether you lose your place behind it.",
    baseline: {
      componentKey: "product/drawer/baseline",
      sourcePath: "src/arms/components/product/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "product/drawer/parti",
      sourcePath: "src/arms/components/product/parti.tsx",
      direction: "marginalia",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus", "loading", "empty", "error", "overflow"]),
    findings: [
      {
        finding: "The drawer slides over the content it relates to",
        whyItHappens: "An overlay is the default drawer behaviour.",
        partiDecision: "The drawer displaces rather than covers, so the row it came from stays visible.",
        result: "The user keeps their position on the board while reading the detail.",
      }
    ],
  },
  {
    slug: "dropdown",
    name: "Dropdown",
    group: "Product",
    brief: "A menu of actions.",
    prompt: "Build a dropdown for Ledgerline, a research workspace for independent investors. A menu of actions.",
    tell: "Open it and read the item labels.",
    baseline: {
      componentKey: "product/dropdown/baseline",
      sourcePath: "src/arms/components/product/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "product/dropdown/parti",
      sourcePath: "src/arms/components/product/parti.tsx",
      direction: "marginalia",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus", "loading", "empty", "error", "overflow"]),
    findings: [
      {
        finding: "Items labelled by system operation rather than user intent",
        whyItHappens: "Menu labels get written from the handler names.",
        partiDecision: "Each item says what happens when it is used, in the interface's voice.",
        result: "The menu can be read without knowing how the feature is implemented.",
      }
    ],
  },
  {
    slug: "command-menu",
    name: "Command Menu",
    group: "Product",
    brief: "Keyboard-first navigation.",
    prompt: "Build a command menu for Ledgerline, a research workspace for independent investors. Keyboard-first navigation.",
    tell: "Look at the empty-query state, and at whether the shortcut is discoverable anywhere else.",
    baseline: {
      componentKey: "product/command-menu/baseline",
      sourcePath: "src/arms/components/product/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "product/command-menu/parti",
      sourcePath: "src/arms/components/product/parti.tsx",
      direction: "marginalia",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus", "loading", "empty", "error", "overflow"]),
    findings: [
      {
        finding: "A generic list of commands with no grouping and no recents",
        whyItHappens: "The command palette is copied structurally without a decision about what it is for here.",
        partiDecision: "Grouped by the two things this user does - resume a thesis, open a filing - with recents first.",
        result: "The palette is faster than the sidebar for the actual common case, which is the only reason to have one.",
      }
    ],
  },
  {
    slug: "toast",
    name: "Toast",
    group: "Product",
    brief: "Transient confirmation.",
    prompt: "Build a toast for Ledgerline, a research workspace for independent investors. Transient confirmation.",
    tell: "Time it. Then check whether the message says what to do if it was wrong.",
    baseline: {
      componentKey: "product/toast/baseline",
      sourcePath: "src/arms/components/product/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "product/toast/parti",
      sourcePath: "src/arms/components/product/parti.tsx",
      direction: "marginalia",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus", "loading", "empty", "error", "overflow"]),
    findings: [
      {
        finding: "A toast that auto-dismisses in three seconds with no undo",
        whyItHappens: "Three seconds is the library default and undo is extra work.",
        partiDecision: "The confirmation stays until dismissed when it reports a destructive change, and carries the reversal.",
        result: "A user who looks away does not lose the only notice that something changed.",
      }
    ],
  },
  {
    slug: "empty-state",
    name: "Empty State",
    group: "Product",
    brief: "Nothing to show, and why.",
    prompt: "Build a empty state for Ledgerline, a research workspace for independent investors. Nothing to show, and why.",
    tell: "The clearest contrast in the library, and the cheapest to fix. Read the two messages.",
    baseline: {
      componentKey: "product/empty-state/baseline",
      sourcePath: "src/arms/components/product/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "product/empty-state/parti",
      sourcePath: "src/arms/components/product/parti.tsx",
      direction: "marginalia",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus", "loading", "empty", "error", "overflow"]),
    findings: [
      {
        finding: "'No results found'",
        whyItHappens: "It is the highest-probability string for an empty container, and it is not wrong - only useless.",
        partiDecision: "Name the filter that caused it and offer to clear it, and distinguish first-run empty from cleared-by-user empty.",
        result: "The user stops having to guess whether the product is broken or their filter is narrow.",
      }
    ],
  },
  {
    slug: "loading-state",
    name: "Loading State",
    group: "Product",
    brief: "Waiting.",
    prompt: "Build a loading state for Ledgerline, a research workspace for independent investors. Waiting.",
    tell: "Check whether a background refresh blanks the screen.",
    baseline: {
      componentKey: "product/loading-state/baseline",
      sourcePath: "src/arms/components/product/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "product/loading-state/parti",
      sourcePath: "src/arms/components/product/parti.tsx",
      direction: "marginalia",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus", "loading", "empty", "error", "overflow"]),
    findings: [
      {
        finding: "A skeleton on every fetch, including background refreshes",
        whyItHappens: "Loading is treated as one state rather than several.",
        partiDecision: "Shape-matched skeletons on first load only; a refresh keeps stale rows on screen with the timestamp dimmed.",
        result: "The user never loses the screen mid-decision because a poll came back slow.",
      }
    ],
  },
  {
    slug: "error-state",
    name: "Error State",
    group: "Product",
    brief: "Something failed.",
    prompt: "Build a error state for Ledgerline, a research workspace for independent investors. Something failed.",
    tell: "Read both messages and count how many of the four questions each one answers.",
    baseline: {
      componentKey: "product/error-state/baseline",
      sourcePath: "src/arms/components/product/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "product/error-state/parti",
      sourcePath: "src/arms/components/product/parti.tsx",
      direction: "marginalia",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "loading", "empty", "error", "overflow"], ["default", "hover", "focus", "loading", "empty", "error", "overflow"]),
    findings: [
      {
        finding: "'Something went wrong. Please try again.'",
        whyItHappens: "It is the safest possible string because it is true of every failure.",
        partiDecision: "Which feed failed, when the data was last good, what to do instead, and a reference to quote.",
        result: "The message becomes an instruction rather than an apology.",
      }
    ],
  },
  {
    slug: "input",
    name: "Input",
    group: "Forms",
    brief: "A single-line text field, in every state it can be in.",
    prompt: "Build a input for Relay, a message-delivery API. A single-line text field, in every state it can be in.",
    tell: "Look at the focus treatment, then at the disabled one. One arm removes the outline; the other changes the rail pattern.",
    baseline: {
      componentKey: "forms/input/baseline",
      sourcePath: "src/arms/components/forms/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "forms/input/parti",
      sourcePath: "src/arms/components/forms/parti.tsx",
      direction: "dispatch-ledger",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "active", "disabled", "error", "success"], ["default", "hover", "focus", "active"]),
    partiStates: states(["default", "hover", "focus", "active", "disabled", "error", "success"], ["default", "hover", "focus", "active", "disabled", "error", "success"]),
    findings: [
      {
        finding: "outline: none on focus, with a coloured border as the replacement",
        whyItHappens: "Removing the default outline is the standard way to make a field look designed, and the replacement usually fails contrast.",
        partiDecision: "A rail pattern change plus a 3:1 boundary, verified rather than assumed.",
        result: "The field stays operable by keyboard for a user who cannot see the border colour change.",
      }
    ],
  },
  {
    slug: "textarea",
    name: "Textarea",
    group: "Forms",
    brief: "Multi-line entry.",
    prompt: "Build a textarea for Relay, a message-delivery API. Multi-line entry.",
    tell: "Type past the visible area in each.",
    baseline: {
      componentKey: "forms/textarea/baseline",
      sourcePath: "src/arms/components/forms/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "forms/textarea/parti",
      sourcePath: "src/arms/components/forms/parti.tsx",
      direction: "dispatch-ledger",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "active", "disabled", "error", "success"], ["default", "hover", "focus", "active"]),
    partiStates: states(["default", "hover", "focus", "active", "disabled", "error", "success"], ["default", "hover", "focus", "active", "disabled", "error", "success"]),
    findings: [
      {
        finding: "A fixed height with an internal scrollbar",
        whyItHappens: "A fixed height is the library default.",
        partiDecision: "Grows to a stated maximum, then scrolls, with the character budget printed.",
        result: "The writer can see what they wrote without scrolling inside a box inside a page.",
      }
    ],
  },
  {
    slug: "select",
    name: "Select",
    group: "Forms",
    brief: "Choosing one of several.",
    prompt: "Build a select for Relay, a message-delivery API. Choosing one of several.",
    tell: "Open both with the keyboard alone.",
    baseline: {
      componentKey: "forms/select/baseline",
      sourcePath: "src/arms/components/forms/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "forms/select/parti",
      sourcePath: "src/arms/components/forms/parti.tsx",
      direction: "dispatch-ledger",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "active", "disabled", "error", "success"], ["default", "hover", "focus", "active"]),
    partiStates: states(["default", "hover", "focus", "active", "disabled", "error", "success"], ["default", "hover", "focus", "active", "disabled", "error", "success"]),
    findings: [
      {
        finding: "A custom listbox without the roles that make it a listbox",
        whyItHappens: "Styling a native select is hard, so it gets replaced with divs that look right.",
        partiDecision: "Native semantics kept and restyled - and where a custom control was genuinely needed, the full role set ships with it.",
        result: "The control announces itself correctly to a screen reader.",
      }
    ],
  },
  {
    slug: "checkbox",
    name: "Checkbox",
    group: "Forms",
    brief: "A binary choice in a set.",
    prompt: "Build a checkbox for Relay, a message-delivery API. A binary choice in a set.",
    tell: "Check the hit area, then check the indeterminate state.",
    baseline: {
      componentKey: "forms/checkbox/baseline",
      sourcePath: "src/arms/components/forms/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "forms/checkbox/parti",
      sourcePath: "src/arms/components/forms/parti.tsx",
      direction: "dispatch-ledger",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "active", "disabled", "error", "success"], ["default", "hover", "focus", "active"]),
    partiStates: states(["default", "hover", "focus", "active", "disabled", "error", "success"], ["default", "hover", "focus", "active", "disabled", "error", "success"]),
    findings: [
      {
        finding: "A 16px box as the entire hit target",
        whyItHappens: "The visual size and the touch target get treated as the same measurement.",
        partiDecision: "The label is part of the target and the whole row reaches 44px.",
        result: "The control is usable on a phone without precision.",
      }
    ],
  },
  {
    slug: "radio",
    name: "Radio",
    group: "Forms",
    brief: "One of several, mutually exclusive.",
    prompt: "Build a radio for Relay, a message-delivery API. One of several, mutually exclusive.",
    tell: "Arrow-key through both groups.",
    baseline: {
      componentKey: "forms/radio/baseline",
      sourcePath: "src/arms/components/forms/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "forms/radio/parti",
      sourcePath: "src/arms/components/forms/parti.tsx",
      direction: "dispatch-ledger",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "active", "disabled", "error", "success"], ["default", "hover", "focus", "active"]),
    partiStates: states(["default", "hover", "focus", "active", "disabled", "error", "success"], ["default", "hover", "focus", "active", "disabled", "error", "success"]),
    findings: [
      {
        finding: "Each radio is separately tabbable",
        whyItHappens: "Rendering a list of inputs produces a list of tab stops unless the roving pattern is deliberate.",
        partiDecision: "One tab stop for the group, arrows to move within it.",
        result: "A keyboard user passes the group in one keystroke instead of five.",
      }
    ],
  },
  {
    slug: "switch",
    name: "Switch",
    group: "Forms",
    brief: "An immediate on/off.",
    prompt: "Build a switch for Relay, a message-delivery API. An immediate on/off.",
    tell: "Look for the label that says what 'on' currently means.",
    baseline: {
      componentKey: "forms/switch/baseline",
      sourcePath: "src/arms/components/forms/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "forms/switch/parti",
      sourcePath: "src/arms/components/forms/parti.tsx",
      direction: "dispatch-ledger",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "active", "disabled", "error", "success"], ["default", "hover", "focus", "active"]),
    partiStates: states(["default", "hover", "focus", "active", "disabled", "error", "success"], ["default", "hover", "focus", "active", "disabled", "error", "success"]),
    findings: [
      {
        finding: "A switch with no state text beside it",
        whyItHappens: "The affordance reads as self-explanatory, so the label gets skipped.",
        partiDecision: "The current state is printed, because a switch's position is ambiguous without one.",
        result: "The user can tell what the setting is rather than inferring it from a knob position.",
      }
    ],
  },
  {
    slug: "date-picker",
    name: "Date Picker",
    group: "Forms",
    brief: "Choosing a delivery time.",
    prompt: "Build a date picker for Relay, a message-delivery API. Choosing a delivery time.",
    tell: "Try to type a date into each.",
    baseline: {
      componentKey: "forms/date-picker/baseline",
      sourcePath: "src/arms/components/forms/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "forms/date-picker/parti",
      sourcePath: "src/arms/components/forms/parti.tsx",
      direction: "dispatch-ledger",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "active", "disabled", "error", "success"], ["default", "hover", "focus", "active"]),
    partiStates: states(["default", "hover", "focus", "active", "disabled", "error", "success"], ["default", "hover", "focus", "active", "disabled", "error", "success"]),
    findings: [
      {
        finding: "A calendar grid with no text entry",
        whyItHappens: "The calendar is the visible part of the pattern, so it becomes the whole pattern.",
        partiDecision: "Typing is the primary path and the calendar is the fallback, with the timezone stated.",
        result: "A user who knows the date they want gets it in four keystrokes.",
      }
    ],
  },
  {
    slug: "form-section",
    name: "Form Section",
    group: "Forms",
    brief: "A group of related fields with a heading.",
    prompt: "Build a form section for Relay, a message-delivery API. A group of related fields with a heading.",
    tell: "Look at where the section explanation sits relative to the fields it explains.",
    baseline: {
      componentKey: "forms/form-section/baseline",
      sourcePath: "src/arms/components/forms/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "forms/form-section/parti",
      sourcePath: "src/arms/components/forms/parti.tsx",
      direction: "dispatch-ledger",
      commands: ["explore", "tokens", "build", "states", "harden"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "active", "disabled", "error", "success"], ["default", "hover", "focus", "active"]),
    partiStates: states(["default", "hover", "focus", "active", "disabled", "error", "success"], ["default", "hover", "focus", "active", "disabled", "error", "success"]),
    findings: [
      {
        finding: "Section help text placed under the heading, away from the field it concerns",
        whyItHappens: "The heading block and the field block get designed as separate units.",
        partiDecision: "Each field's constraint sits with the field, in the key gutter.",
        result: "The reader never has to hold an explanation in memory while scrolling to the input.",
      }
    ],
  },
  {
    slug: "article-header",
    name: "Article Header",
    group: "Content",
    brief: "The head of a documentation page.",
    prompt: "Build a article header for Relay, a message-delivery API. The head of a documentation page.",
    tell: "Check what metadata each carries, and whether it is useful mid-integration.",
    baseline: {
      componentKey: "content/article-header/baseline",
      sourcePath: "src/arms/components/content/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "content/article-header/parti",
      sourcePath: "src/arms/components/content/parti.tsx",
      direction: "dispatch-ledger",
      commands: ["explore", "tokens", "build", "deslop"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "overflow", "empty"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "overflow", "empty"], ["default", "hover", "focus", "overflow", "empty"]),
    findings: [
      {
        finding: "Title, author avatar and reading time",
        whyItHappens: "Article headers in the training set are blog headers.",
        partiDecision: "Method, path, stability, and the version the page describes.",
        result: "The metadata answers the questions an integrating engineer actually has.",
      }
    ],
  },
  {
    slug: "docs-nav",
    name: "Documentation Navigation",
    group: "Content",
    brief: "The sidebar of an API reference.",
    prompt: "Build a documentation navigation for Relay, a message-delivery API. The sidebar of an API reference.",
    tell: "Look at how the current page is marked, and how deep the tree goes before it collapses.",
    baseline: {
      componentKey: "content/docs-nav/baseline",
      sourcePath: "src/arms/components/content/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "content/docs-nav/parti",
      sourcePath: "src/arms/components/content/parti.tsx",
      direction: "dispatch-ledger",
      commands: ["explore", "tokens", "build", "deslop"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "overflow", "empty"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "overflow", "empty"], ["default", "hover", "focus", "overflow", "empty"]),
    findings: [
      {
        finding: "Every section expanded, with the current page marked by colour only",
        whyItHappens: "Expanding everything avoids a decision about hierarchy.",
        partiDecision: "The current section expanded and the rest collapsed, current page marked by rail pattern and weight.",
        result: "The nav fits on a screen and the position is findable without colour.",
      }
    ],
  },
  {
    slug: "code-block",
    name: "Code Block",
    group: "Content",
    brief: "A request sample.",
    prompt: "Build a code block for Relay, a message-delivery API. A request sample.",
    tell: "Copy from both. Then check whether the line numbers came with it.",
    baseline: {
      componentKey: "content/code-block/baseline",
      sourcePath: "src/arms/components/content/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "content/code-block/parti",
      sourcePath: "src/arms/components/content/parti.tsx",
      direction: "dispatch-ledger",
      commands: ["explore", "tokens", "build", "deslop"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "overflow", "empty"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "overflow", "empty"], ["default", "hover", "focus", "overflow", "empty"]),
    findings: [
      {
        finding: "Line numbers rendered as text inside the code",
        whyItHappens: "Numbers as markup is the simplest implementation.",
        partiDecision: "A CSS counter, so a copy takes the code and nothing else.",
        result: "The pasted sample runs.",
      }
    ],
  },
  {
    slug: "timeline",
    name: "Timeline",
    group: "Content",
    brief: "A delivery event sequence.",
    prompt: "Build a timeline for Relay, a message-delivery API. A delivery event sequence.",
    tell: "Check whether the timeline encodes real elapsed time or only order.",
    baseline: {
      componentKey: "content/timeline/baseline",
      sourcePath: "src/arms/components/content/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "content/timeline/parti",
      sourcePath: "src/arms/components/content/parti.tsx",
      direction: "dispatch-ledger",
      commands: ["explore", "tokens", "build", "deslop"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "overflow", "empty"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "overflow", "empty"], ["default", "hover", "focus", "overflow", "empty"]),
    findings: [
      {
        finding: "Evenly spaced events regardless of the gaps between them",
        whyItHappens: "Even spacing is what a list produces.",
        partiDecision: "Offsets from t0 printed, with retry intervals visible as intervals.",
        result: "The retry ladder is legible as a ladder, which is the reason to draw it as a timeline at all.",
      }
    ],
  },
  {
    slug: "comparison-table",
    name: "Comparison Table",
    group: "Content",
    brief: "Two options, dimension by dimension.",
    prompt: "Build a comparison table for Relay, a message-delivery API. Two options, dimension by dimension.",
    tell: "Read a row at 375px in each.",
    baseline: {
      componentKey: "content/comparison-table/baseline",
      sourcePath: "src/arms/components/content/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "content/comparison-table/parti",
      sourcePath: "src/arms/components/content/parti.tsx",
      direction: "dispatch-ledger",
      commands: ["explore", "tokens", "build", "deslop"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "overflow", "empty"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "overflow", "empty"], ["default", "hover", "focus", "overflow", "empty"]),
    findings: [
      {
        finding: "A three-column table that scrolls horizontally on mobile",
        whyItHappens: "Horizontal scroll is the default table fallback.",
        partiDecision: "Below the breakpoint the table becomes stacked pairs, one dimension per block.",
        result: "The comparison is readable on a phone rather than merely present.",
      }
    ],
  },
  {
    slug: "metadata",
    name: "Metadata",
    group: "Content",
    brief: "Key-value facts about a page or object.",
    prompt: "Build a metadata for Relay, a message-delivery API. Key-value facts about a page or object.",
    tell: "Check the alignment of the values.",
    baseline: {
      componentKey: "content/metadata/baseline",
      sourcePath: "src/arms/components/content/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "content/metadata/parti",
      sourcePath: "src/arms/components/content/parti.tsx",
      direction: "dispatch-ledger",
      commands: ["explore", "tokens", "build", "deslop"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "overflow", "empty"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "overflow", "empty"], ["default", "hover", "focus", "overflow", "empty"]),
    findings: [
      {
        finding: "Key and value in a flowing paragraph or an uneven two-column list",
        whyItHappens: "Definition lists get styled as prose.",
        partiDecision: "The same key gutter every other record uses, so values align down the page.",
        result: "The block is scannable by column, which is the only reason to tabulate it.",
      }
    ],
  },
  {
    slug: "breadcrumbs",
    name: "Breadcrumbs",
    group: "Content",
    brief: "Where this page sits.",
    prompt: "Build a breadcrumbs for Relay, a message-delivery API. Where this page sits.",
    tell: "Check what the last item is, and whether it is a link.",
    baseline: {
      componentKey: "content/breadcrumbs/baseline",
      sourcePath: "src/arms/components/content/baseline.tsx",
      rationale: "Built cold from the brief with no design skill loaded: conventional structure, a neutral ramp with one brand accent, spacing chosen per component, and the ideal state implemented first.",
    },
    parti: {
      componentKey: "content/breadcrumbs/parti",
      sourcePath: "src/arms/components/content/parti.tsx",
      direction: "dispatch-ledger",
      commands: ["explore", "tokens", "build", "deslop"],
      rationale: "Built to a direction derived from the subject's own material, with a declared token set used for every value and every named state shipped in the same pass rather than as follow-up work.",
    },
    states: states(["default", "hover", "focus", "overflow", "empty"], ["default", "hover", "focus"]),
    partiStates: states(["default", "hover", "focus", "overflow", "empty"], ["default", "hover", "focus", "overflow", "empty"]),
    findings: [
      {
        finding: "The current page rendered as a link to itself",
        whyItHappens: "Mapping an array to links produces a link for every item.",
        partiDecision: "The current page is marked with aria-current and is not a link.",
        result: "The trail says where you are, rather than offering to take you where you already are.",
      }
    ],
  },
];

export const COMPONENT_GROUPS = ["Marketing", "Product", "Forms", "Content"] as const;

export function pairsByGroup(group: string): ComponentPair[] {
  return COMPONENT_PAIRS.filter((c) => c.group === group);
}

export function pairBySlug(slug: string): ComponentPair | undefined {
  return COMPONENT_PAIRS.find((c) => c.slug === slug);
}

export function componentSlugs(): string[] {
  return COMPONENT_PAIRS.map((c) => c.slug);
}
