#!/usr/bin/env node
// Wrap one element in source into N variant siblings, so the browser can switch
// between them and accept.mjs can collapse them again exactly.
//
//   node live/wrap.mjs --file src/Hero.tsx --line 42 --variants A,B,C
//   node live/wrap.mjs --file page.html --anchor '<h1 id="headline"' --variants A,B
//
// The marker goes ON the element, not on a new wrapper div. A wrapper changes the
// parent's layout - a flex or grid child suddenly nested one level deeper moves -
// and a variant mechanism that moves the thing being judged is worse than useless.
//
// Writes a manifest and a full-file backup under the session directory, so accept
// and discard are restores rather than reconstructions.

import fs from 'node:fs';
import path from 'node:path';
import {
  elementRange, findVariantBlocks, withVariantAttr,
  lineToIndex, indexToLine, indentAt, detectEol, toLf, toEol,
} from './markup.mjs';

const args = new Map();
for (let i = 2; i < process.argv.length; i++) {
  const a = process.argv[i];
  if (!a.startsWith('--')) continue;
  const next = process.argv[i + 1];
  if (!next || next.startsWith('--')) args.set(a.slice(2), true);
  else { args.set(a.slice(2), next); i++; }
}

// Always terminates. An `out` that returns on success lets a handled branch fall
// through into the next one - undo would print its result and then run accept.
const out = (payload) => {
  console.log(JSON.stringify(payload, null, 2));
  process.exit(payload.ok ? 0 : 1);
};

const file = args.get('file');
const session = args.get('session');
if (!file) out({ ok: false, error: 'file_required' });
if (!fs.existsSync(file)) out({ ok: false, error: 'file_not_found', file });

// Refuse to wrap anything that is not source. Accepting a variant into a build
// artifact is silent data loss: the next build overwrites it and the user's chosen
// design disappears with no error anywhere. Checked before the file is read for
// content, because the cheapest refusal is the one that happens first.
const BUILD_DIRS = new Set([
  'node_modules', 'dist', 'build', 'out', '.next', '.nuxt', '.output', '.svelte-kit',
  'coverage', 'vendor', '.parti',
]);

function notSource(target) {
  // Judge the path by its own segments, not by its relation to the cwd. Relative
  // paths are unreliable across drives on Windows and would refuse every file in a
  // temp directory on POSIX - a portability trap that makes the guard fire for the
  // wrong reason on one platform and not at all on the other.
  const segments = path.resolve(target).split(/[\\/]+/);
  const hit = segments.slice(0, -1).find((s) => BUILD_DIRS.has(s));
  if (hit) return `inside ${hit}/, which is build output`;
  if (/\.(min|bundle)\.[a-z]+$/i.test(segments.at(-1))) return 'a minified or bundled artifact';
  const head = fs.readFileSync(target, 'utf8').slice(0, 600).toLowerCase();
  if (/@generated|do not edit|auto-?generated|code generated by/.test(head)) {
    return 'marked generated in its header';
  }
  return null;
}

const why = notSource(file);
if (why) {
  out({
    ok: false,
    error: 'not_source',
    reason: why,
    file,
    hint: 'find the source this file is built from and wrap that; a variant accepted here is erased by the next build',
  });
}

const raw = fs.readFileSync(file, 'utf8');
const eol = detectEol(raw);
const src = toLf(raw);

// Refuse to nest. A second wrap over a live one produces variants of variants and
// there is no sane way to collapse that.
const existing = findVariantBlocks(src);
if (existing.length) {
  out({
    ok: false,
    error: 'already_wrapped',
    variants: existing.map((b) => b.name),
    hint: 'run accept.mjs (--variant X or --discard) before wrapping again',
  });
}

// Find where the target element starts.
function resolveStart() {
  if (args.get('anchor')) {
    const anchor = String(args.get('anchor'));
    const first = src.indexOf(anchor);
    if (first === -1) return { error: 'anchor_not_found' };
    if (src.indexOf(anchor, first + 1) !== -1) return { error: 'anchor_not_unique' };
    // Step back to the opening `<` of the tag the anchor lands in.
    const open = src.lastIndexOf('<', first);
    return open === -1 ? { error: 'anchor_not_in_tag' } : { index: open };
  }
  if (args.get('line')) {
    const from = lineToIndex(src, Number(args.get('line')));
    const open = src.indexOf('<', from);
    if (open === -1) return { error: 'no_tag_at_or_after_line' };
    return { index: open };
  }
  return { error: 'line_or_anchor_required' };
}

const found = resolveStart();
if (found.error) out({ ok: false, error: found.error });

const range = elementRange(src, found.index);
if (!range) {
  out({
    ok: false,
    error: 'unbalanced_element',
    hint: 'the tag at this position never closes; point at a complete element',
  });
}

const names = String(args.get('variants') || 'A,B,C')
  .split(',').map((s) => s.trim()).filter(Boolean);
if (names.length < 2) out({ ok: false, error: 'need_at_least_two_variants' });
if (new Set(names).size !== names.length) out({ ok: false, error: 'duplicate_variant_names' });

// Insert mode: the user pointed at a gap, not an element. The anchor stays exactly
// as it is and N empty marked siblings are placed beside it for the agent to fill.
const position = args.get('position');
if (position && position !== 'before' && position !== 'after') {
  out({ ok: false, error: 'bad_position', got: position, expected: ['before', 'after'] });
}

const original = position
  ? null
  : src.slice(range.start, range.end);
const indent = indentAt(src, range.start);

// In JSX, an element sitting in expression position (`return (<X/>)`,
// `{cond && <X/>}`, `=> <X/>`) cannot become three siblings - adjacent elements
// there are a syntax error. A fragment is the only wrapper that adds no DOM node
// and no layout, so it is the one case where wrapping is correct.
const isJsx = /\.(jsx|tsx|mdx)$/i.test(file);
const preceding = src.slice(0, range.start).replace(/\s+$/, '');
const needsFragment =
  isJsx && (/(?:=>|[({&|?:=,])$/.test(preceding) || /\breturn$/.test(preceding));

// An inserted variant starts empty on purpose. Seeding it with a copy of the anchor
// would make every "add something here" begin as a duplicate of its neighbour, which
// is the strongest possible nudge toward the least interesting answer.
const blocks = position
  ? names.map((n) => `<div data-parti-variant="${n}"></div>`)
  : names.map((n) => withVariantAttr(original, n));
if (blocks.some((b) => b === null)) out({ ok: false, error: 'could_not_mark_element' });

// Siblings are separated by a newline plus the original indentation, so the file
// still reads like something a person wrote.
const inner = needsFragment ? `${indent}  ` : indent;
const joined = blocks.join(`\n${inner}`);
const replacement = needsFragment ? `<>\n${inner}${joined}\n${indent}</>` : joined;

// Replace mode swaps the element for the variants. Insert mode keeps the anchor
// untouched and places the variants beside it.
const anchorText = src.slice(range.start, range.end);
const body =
  position === 'before' ? `${replacement}\n${indent}${anchorText}`
  : position === 'after' ? `${anchorText}\n${indent}${replacement}`
  : replacement;
const next = src.slice(0, range.start) + body + src.slice(range.end);

// Backup before touching anything. Discard restores this byte for byte.
const dir = session || path.join('.parti', 'live', 'adhoc');
const backupDir = path.join(dir, 'backups');
fs.mkdirSync(backupDir, { recursive: true });
const backup = path.join(backupDir, `${Date.now()}-${path.basename(file)}`);
fs.writeFileSync(backup, raw);

fs.writeFileSync(file, toEol(next, eol));

// Report where each variant landed so the agent edits the right lines instead of
// re-searching a file it just changed.
const fragmentLead = needsFragment ? 2 + 1 + inner.length : 0; // "<>" + newline + indent
const anchorLead = position === 'after' ? anchorText.length + 1 + indent.length : 0;
let cursor = range.start + fragmentLead + anchorLead;
const placed = names.map((name, i) => {
  const start = cursor;
  const end = start + blocks[i].length;
  cursor = end + 1 + inner.length;
  return {
    name,
    startLine: indexToLine(next, start),
    endLine: indexToLine(next, end),
  };
});

const manifest = {
  file: path.resolve(file),
  backup: path.resolve(backup),
  eol: eol === '\r\n' ? 'crlf' : 'lf',
  variants: names,
  wrappedAt: new Date().toISOString(),
  originalRange: { start: range.start, end: range.end },
  tag: range.tag.name,
  fragment: needsFragment,
  mode: position ? 'insert' : 'replace',
  position: position || undefined,
};
fs.writeFileSync(path.join(dir, 'wrap.json'), JSON.stringify(manifest, null, 2));

out({
  ok: true,
  file,
  tag: range.tag.name,
  fragment: needsFragment,
  mode: position ? 'insert' : 'replace',
  variants: placed,
  manifest: path.join(dir, 'wrap.json'),
  note: position
    ? `${names.length} empty variants placed ${position} the anchor; fill each with a different answer to the brief`
    : `every variant is currently identical to the original; edit ${names.slice(1).join(', ')} to differ on one axis`,
});
